In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [2]:
bankdata = pd.read_excel(r'C:\Users\Big data\Desktop\class\funcardproject\斷詞與和卡額度_20群.xls',encoding='utf-16')
#去除缺失值
bankdata =bankdata.dropna(
    axis=0,     # 0: 对行进行操作; 1: 对列进行操作
    how='any'   # 'any': 只要存在 NaN 就 drop 掉; 'all': 必须全部是 NaN 才 drop 
    )

In [3]:
bankdata.shape

(1680, 10)

In [4]:
X = bankdata.loc[:, ["age","serveTime","Loan","SalPerY","holdCard","Career"]]
y = bankdata.loc[:, ["credLimit_group"]]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)


In [17]:
type(svclassifier)

sklearn.svm.classes.SVC

In [18]:

svclassifier = SVC()
svclassifier=svclassifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [32]:
y_pred = svclassifier.predict(X_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print('--')
print(classification_report(y_test, y_pred))


[[20 51  8  1  1  0  0  0  0  0  0  0  0  0]
 [ 5 99 16  2  1  1  0  0  0  0  0  0  0  0]
 [ 3 75 17  5  2  0  0  0  0  0  0  0  0  0]
 [ 2 47  8  8  2  0  0  0  1  0  0  0  0  0]
 [ 1 34  8  3  3  0  0  0  0  0  0  0  0  0]
 [ 0 13  0  3  0  0  0  0  0  0  0  0  0  0]
 [ 1 21  1  2  1  1  3  0  0  0  0  0  0  0]
 [ 0  7  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0]]
--
              precision    recall  f1-score   support

         0.0       0.62      0.25      0.35        81
         1.0       0.27      0.80      0.40       124
         2.0       0.28      0.17      0.21       102
         3.0       0.32      0.12      0.17        68
         4.0       0.30      0.06      0.10        49
         5.0       0.00      0.00      0.

In [ ]:

svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# 測試 小綠同學

In [22]:
小綠 = pd.DataFrame(columns=["age","serveTime","Loan","SalPerY","holdCard","Career"])
小綠.loc[0]=8,120,4,600000,1,1
小綠.loc[1]=280,120,3,600000000,1,1
小綠.loc[2]=28,12,0,87,2,0
小綠.loc[3]=28,12,0,8700,2,0
小綠

age serveTime Loan    SalPerY holdCard Career
0    8       120    4     600000        1      1
1  280       120    3  600000000        1      1
2   28        12    0         87        2      0
3   28        12    0       8700        2      0

In [23]:
# 他給出的是每一群的機率(相加為一)
preds = svclassifier.predict(小綠)
#接著我們找出裡面機率最大的值的所在位子
print(np.where(preds[1]==np.max(preds[1])))

(array([0], dtype=int64),)


In [13]:
小綠群=[print("第",str(i),"個小綠被分在第",preds[i],"群") for i in range(len(小綠))]

第 0 個小綠被分在第 1.0 群
第 1 個小綠被分在第 1.0 群
第 2 個小綠被分在第 1.0 群
第 3 個小綠被分在第 1.0 群


In [30]:
小綠[1:2]

age serveTime Loan    SalPerY holdCard Career
1  280       120    3  600000000        1      1

In [31]:
svclassifier.predict(小綠[1:2])

array([1.])